name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    env:
      DB_CONNECTION: mysql
      DB_HOST: 127.0.0.1
      DB_PORT: 3006
      DB_DATABASE: 'laravel'
      DB_USERNAME: root
      DB_PASSWORD: '123456'

    steps:
    - uses: shogo82148/actions-setup-mysql@v1
      with:
        mysql-version: '8.0'
        root-password: '123456'
        auto-start: true
    - run: sudo mysql -e 'SELECT version()'
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Running php tests
      run: ./vendor/bin/phpunit
